### ISSUE TITLE
Minor unit conversion issue that messes the simulation up

### ISSUE THREAD

**Issue by We1chJ** [4201VitruvianBots/2021SwerveSim#2]
Hi I am Jack W, main programmer from 2877 Ligerbots. I was recently checking out this repo and try to figure out how to sim a swerve drive as we are interested to introduce swerve drive to our team in the future. I tried to run this code and everything looks fine but the simulation is incorrect, that is the robot doesn't seem to be able to rotate independently while maintaining the field relative movement in x and y direction. So I played around with the code myself and I discovered that it is actually doing the math and code correctly, but there is a minor unit coversion that makes the robot rotate crazily, which makes me think that it is actually not strafing in a field-relative way.

In short, I was trying to run the modified version of SwerveControllerCommand in this repo. And the method in DriveSubsystem.java--
public double getHeading() {
    return m_gyro.getRotation2d().getDegrees();
  }
returns in degrees, but when it is called to update the swerve odometry as well as when updating the poses of the swerve modules,  the degree values are used in the constructor of Rotation2d(), which should take in angles in radians instead of degrees. So I think if you get rid of the .getDegrees() part, everything will be fine.

I didn't submit a pull requests or other ways to point this out because it is actually a very minor mistake, and this is probably not the most proper way. But please update it so that other people hopefully will not get confused as I was :)

**Comment by jonathandao0** [comment]
Hi Jack,

I've fixed it to the correct units/naming. Thanks for bug report!
